### ISSUE TITLE
Exception in test execution

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-vnv-executor#79]
TEST VERSION : https://pre-int-vnv-bcn.5gtango.eu/validation-and-verification/tests/0dbcf880-b295-46e8-a754-4415de544c7e

ENVIRONMENT:  https://pre-int-vnv-bcn.5gtango.eu

2019-12-09 09:53:12.684 | pre-int-vnv-bcn | tng-vnv-executor
-- | -- | --
Error validating 366a9b5b-581d-46d5-8cfb-cd93f4c6df6d-null: java.lang.NullPointerException: Cannot invoke method size() on null object

find full error stack trace here

http://logs.sonata-nfv.eu/search?rangetype=absolute&fields=source%2Ccontainer_name%2Cmessage&width=2048&highlightMessage=&from=2019-12-09T09%3A52%3A53.736Z&to=2019-12-09T09%3A53%3A12.748Z&q=source%3Apre-int-vnv-bcn+AND+(container_name%3A*executor*+)+

**Comment by sinaure** [comment]
but probe is successfully executed 

container_name
366a9b5b-581d-46d5-8cfb-cd93f4c6df6d_mqttprobe_1

**Comment by tblanco219** [comment]
TD is wrong. Name "parser" in verification not match in exercise's steps. 

Here you can review an example: https://github.com/sonata-nfv/tng-tests/blob/master/packages/TSTIMPSP/Definitions/test-descriptor.yml, where validation test "parser" exists in execution step.

**Comment by sinaure** [comment]
ok so the test descriptor structure has been changed from Vigo?

**Comment by santiagordguez** [comment]
No, it doesn't. 

If you need to generate a validation for an execution test, this validation need to be linked to an exercise step by name. 

You're using a validation named "parser" but the test descriptor only contains a "mqttprobe" exercise step. If you check the example provided by @tblanco219 you will see a validation parser and a validation exercise step.
